### ISSUE TITLE
On first log in, all contacts appear offline sometimes

### ISSUE THREAD

**Issue by limitedmage** [lhchavez/gtalkchat#1]

**Comment by lhchavez** [comment]
This is due to the fact that the initial roster is loaded after the first <presence/> stanza is sent (which is the event I chose to signal that the user is now online). I think I will delay that event on the server (which will become a ~1s delay to the first log in) for a certain amount of time.

**Comment by limitedmage** [comment]
Fix does not work for me :(

**Comment by limitedmage** [comment]
I think I've got a pretty consistent repro for this:
If I log in as "limited.mage@gmail.com" or just "limited.mage", all contacts load fine and show correct status.
If I log in as "limitedmage" (with no dot), all contacts appear offline. This will fix itself after a while, though. Just closing and reopening the app SOMETIMES works, but usually it takes many restarts to show correct contact details.

**Comment by lhchavez** [comment]
thanks to your repro steps, i fixed it on the server. while most xmpp stanzas accept a non-canonical username (with different usage of dots), `google:shared-status` will only accept your canonical username. fixed it by setting the username to the first part of the jid.
