### ISSUE TITLE
Tiles do not contain friends' images

### ISSUE THREAD

**Issue by mattleech** [lhchavez/gtalkchat#103]
None of my friends' images show up on the live tiles, online contacts list or recent tiles.

**Comment by omniwolf** [comment]
not much to add, but me too.

running HTC HD7 (T9296), WP7.5
OS version 7.10.7720.68

**Comment by limitedmage** [comment]
Are you still having this issue in 1.5?

**Comment by limitedmage** [comment]
Closing for lack of feedback, please reopen if this issue is still happening.
