### ISSUE TITLE
Gchat crashes when sending messages

### ISSUE THREAD

**Issue by tomchop** [lhchavez/gtalkchat#106]
Gchat launches, the contact list loads just fine, but the images fail to load (grey squares instead).

After selecting an online contact and trying to send him/her a message, Gchat takes a long while "sending" the message before crashing (without the message being sent).

I suspect this is due to the fact that I'm using two-step authentication with my Google account. I tried switching back to one-step authentication just for the sake of trying and it seemed to word _better_ but still really slow and sometimes crashed).

I have the latest version of Mango and I've send the crash reports accordingly.

Thanks !

**Comment by lhchavez** [comment]
Will take a look into it, expect a fix on the next release.

Thanks for reporting this!

On Mon, Dec 12, 2011 at 8:38 AM, tomchop <
reply@reply.github.com

**Comment by MaidenOfTheSpear** [comment]
Mine does the same. Except I don't know about the one-step or two-stop thing. Is there anything I can do to change it??

**Comment by jkendle** [comment]
I am also experiencing this problem. I have been sending the crash reports as well.

**Comment by carera** [comment]
Evening. Just curious about when is the new release planned, because it's crashing on sending a message also on my Nokia Lumia 710. Thanks

**Comment by vanquish83** [comment]
Same problem here. App is unusable. Developers have any news about that? it seems that developers give up with this project....

**Comment by vanquish83** [comment]
... Hello? Can anyone give us some more feedback when/if this issue will be fixed?

**Comment by limitedmage** [comment]
This has been fixed in 1.5
