### ISSUE TITLE
Go offline without log out

### ISSUE THREAD

**Issue by mersadk** [lhchavez/gtalkchat#107]
I would like to be able to go offline without logging out so I don't have to enter mail and password each time a want to switch to online.

Otherwise great app :)

**Comment by vanquish83** [comment]
I think that Project is no longer supported by authors.
There are many request of bugfixes and new feature but in 3 months no word about authors.

**Comment by lhchavez** [comment]
I'll implement invisible instead of offline.

**Comment by lhchavez** [comment]
This is a dupe of #84.

**Comment by limitedmage** [comment]
This is basically a dupe of #84, so closing this one
