### ISSUE TITLE
Gchat doesn't receive messages from Blackberry google chat client

### ISSUE THREAD

**Issue by mishanctrl** [lhchavez/gtalkchat#134]
I have found that I do not receive messages in Gchat that have been sent from the official google chat app for Blackberry. The messages show up in the chat log when checked on a computer but are never received by the Gchat app.

**Comment by limitedmage** [comment]
Related to #131?

**Comment by limitedmage** [comment]
Migrated to https://github.com/gchatapp/gtalkchat/issues/20
