### ISSUE TITLE
Your own account appears as a contact

### ISSUE THREAD

**Issue by lhchavez** [lhchavez/gtalkchat#137]

**Comment by MeganByte** [comment]
Doesn't always happen but it does sometimes even when I'm invisible, which confused me. LG E900

**Comment by zl4bv** [comment]
This happens for me when I'm logged into Google Talk somewhere else (in my case, on the Gmail website).

**Comment by MobileRob** [comment]
I get this every time I go into the app.  My email shows up with my profile picture in the list of online contacts.

**Comment by limitedmage** [comment]
Migrated to https://github.com/gchatapp/gtalkchat/issues/4
