### ISSUE TITLE
Chinese-characters contact name not displayed in "all" list

### ISSUE THREAD

**Issue by kaneboy** [lhchavez/gtalkchat#138]
I am a gchat user from China. In my gtalk friends list, some contacts's name contains Chinese characters. If a contact's name contains Chinese characters, he will not be displayed in "all" list. But if I tap search appbar button to have a search, they can be searched and displayed correctly.

**Comment by limitedmage** [comment]
Migrated to https://github.com/gchatapp/gtalkchat/issues/9
