### ISSUE TITLE
AIM federation contacts not working

### ISSUE THREAD

**Issue by MobileRob** [lhchavez/gtalkchat#139]
I have several contacts that I IM with for business that use AIM and work with my Talk app on my android device and on Google Chat or Talk on the desktop.

However, when they send me messages, I get them on my desktop and android phone, but do not get them in GChat+ on my Windows 7 phone.  Is there something I need to set to get this to work.

All of my gmail (Google Chat) contacts work fine.

Thanks.
Rob.

**Comment by limitedmage** [comment]
Migrated to https://github.com/gchatapp/gtalkchat/issues/20
