### ISSUE TITLE
Always switches back to available status message

### ISSUE THREAD

**Issue by Shaaz** [lhchavez/gtalkchat#141]
Hi I am using the app on the Lumia 920 and  I log in and it always switches to available status message  (I prefer to have it in busy or invisible). Furthmore it changes the status on the other clients (google talk on my computer). I was wondering if this is an issue with switching to windows phone 8 or lumia problem

**Comment by limitedmage** [comment]
Hi Shaaz,
This is a known issue and is here if you want to follow it: https://github.com/gchatapp/gtalkchat/issues/5
