### ISSUE TITLE
No notification when phone is blocked

### ISSUE THREAD

**Issue by mirsa** [lhchavez/gtalkchat#144]
Hi,

I just bought your app for my Nokia Lumia 710 but I don't receive any notification or sound when the phone is blocked (which is almost all the time). Is it possible to change this?

Cheers

**Comment by limitedmage** [comment]
Hi Mirsa,

Do you have cellular connection on? If you only have WiFi, Windows Phone may turn it off to save battery when the phone is locked. Do you get notifications when you are using the phone but in another app? Do you get notifications when the phone is locked and you are using cellular connection?

**Comment by limitedmage** [comment]
Also, migrating to https://github.com/gchatapp/gtalkchat/issues/26
