### ISSUE TITLE
gtalk chat too slow

### ISSUE THREAD

**Issue by julesonlinegoa** [lhchavez/gtalkchat#145]
I bought this gtalk chat+ today and i noticed that it is very slow at sending and receiving messages. also it takes forever to load the contact list.

**Comment by limitedmage** [comment]
We are continuously trying to improve performance. Gchat's performance varies greatly depending on network connection and phone processing power. For best results, try using Gchat on WiFi. Which phone do you have?

**Comment by julesonlinegoa** [comment]
I have the Nokia Lumia 920. On Lock screen the GChat+ gets disconnected and i cant receive any messages.

**Comment by limitedmage** [comment]
Are you using WiFi or 3G? Windows Phone will disconnect from WiFi when the screen is locked.

**Comment by julesonlinegoa** [comment]
i use Wi-Fi when available and 3G when Wi-Fi is not available.

**Comment by limitedmage** [comment]
With 3G turned on, do you get message notifications when Gchat is not running? Either when the phone is locked or when using another app.

**Comment by julesonlinegoa** [comment]
i dont get message notifications from gchat when phone is locked. although i do get message notifications when gchat is open and im using other apps.

**Comment by limitedmage** [comment]
If you get message notifications when the phone is on and Gchat is not running, then there is no problem on our end. It's probably an issue with your 3G or WiFi connection. Windows Phone turns WiFi off when the phone is locked to save battery.
