### ISSUE TITLE
Google Apps accounts do not work

### ISSUE THREAD

**Issue by zakx2008** [lhchavez/gtalkchat#146]
If your username has a domain of anything other than @gmail.com, the application will not be able to log in.

**Comment by limitedmage** [comment]
Google Apps works perfectly for me... What error do you get? Do you have two-step authentication enabled? If so, follow instructions here: http://support.google.com/accounts/bin/answer.py?hl=en&answer=185833

**Comment by zakx2008** [comment]
I don't have two step authentication enabled. I'm getting an authentication error when I try to log in, it says invalid username / password.

**Comment by zakx2008** [comment]
If it helps, my account's domain is @g.rit.edu

**Comment by zakx2008** [comment]
Apologies, it appears that there was a problem with my account, I got it working, thank you for your quick response.

**Comment by limitedmage** [comment]
Glad to know it's working now :)
