### ISSUE TITLE
feature request: XEP-0280: Message Carbons

### ISSUE THREAD

**Issue by mazursky** [lhchavez/gtalkchat#147]
I log to it simultaneously from my Windows phone and from the gmail.com.

When I chat in GChat, my dialog automatically appears on gmail' s gtalk as if I were chatting from the web.

I'd like very much to have this feature in GChat: when I chat on the web, my dialog automatically appears in GChat's history.

**Comment by limitedmage** [comment]
Moved to https://github.com/gchatapp/gtalkchat/issues/28
