### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by altano** [lhchavez/gtalkchat#149]
Every time I open the app I get the error "unable to connect to server".  I tried on both wifi and LTE, and on two different phones.  I'm having no other connection issues on my phone.

**Comment by xcerk32** [comment]
I have the same problem :( 
The app used to be good,but now...
Does anybody know what can I do or what is the reason of that?

**Comment by irishairisha** [comment]
I have same complaint..i have already paid for this application
