### ISSUE TITLE
Server timeout is too short on a slow connection

### ISSUE THREAD

**Issue by amodmallya** [lhchavez/gtalkchat#51]
Hey,

Firstly i would like to thank you for providing with this app for wp7 users.

Now to the issue. I am getting this error everytime i start the application. I am trying to logging using a slower 2G connection. Is that the reason why its not connecting, although in my opinion that should not be a problem. I was able to log in using my wifi connection

If there is a work around, can you please provide me with one. 

Thank you.

Regards,
Amod Mallya

**Comment by limitedmage** [comment]
Right now there's a 5-second timeout for connections. Maybe changing this value will help users on slow connections?

**Comment by amodmallya** [comment]
Thank you for the reply. Is there something I need to do on my end? Because my android phone does not face this problem when i log into gtalk or anyother google application really

**Comment by limitedmage** [comment]
The timeout is hardcoded, so there's nothing you can do except download the source code, change the value and try. We'll do some testing to see what the best value for the timeout is. 5 seconds is usually large enough, but apparently not for certain tests.

**Comment by amodmallya** [comment]
ok... i will check it out..thanks :)
