### ISSUE TITLE
24hrs signed in timeout for Gchat+ users

### ISSUE THREAD

**Issue by dajunga** [lhchavez/gtalkchat#56]
Gchat Ver: 1.2

Once you open the app it appears to be very responsive. When you exit out of the app by hitting the home button for example and let it sit idle (I've done about a couple of hours of wait) it will no longer receive new messages.

*Otherwise love the app when it works. Nice work!

**Comment by limitedmage** [comment]
The limits for the server to maintain you online (as in https://github.com/lhchavez/gtalkjsonproxy/blob/master/gtalk.js ) are the following:
15 minutes for away
30 minutes for extended away
2 hours for offline

If you open the app again these counters will be reset. These timeouts are necessary for ensuring the server does not overload.

**Comment by dajunga** [comment]
Thanks for the explanation. This is unfortunate considering most people would love to use this as an alternative to SMS. With this limitation it appears we are not there yet. What will it take to increase these limits on the server? Would a paid app help to scale the capacity of the server?

**Comment by limitedmage** [comment]
We're discussing how best this might be implemented. What we don't want is to overload the server by pushing notifications to inactive users.

**Comment by dajunga** [comment]
That's understandable though unfortunately that is probably the most common use case - where a user is inactive but would like to be notifiable. I hope you are able to find a solution to this - I love the app! I paid $9.99 for the IM+ and have been utterly disappointed. I would be more than happy to pay for Gchat to help fund the development effort to get these issues resolved.

**Comment by lhchavez** [comment]
We have decided to leave the timeout limits as they are for the free version, and will increase the limit for the Plus version (in the 24-48 hour range), starting with version 1.5.

**Comment by dajunga** [comment]
Great news! When do you expect version 1.5 to be available?

On Fri, Nov 11, 2011 at 11:38 AM, lhchavez
reply@reply.github.com
wrote:

**Comment by limitedmage** [comment]
We just submitted 1.4 to the Marketplace and don't yet have a timeframe for 1.5. You can keep track of it here: https://github.com/lhchavez/gtalkchat/issues?milestone=6&amp;state=open

**Comment by dajunga** [comment]
Thanks! I have already purchased and installed ver 1.3 - so I should
get notified when your updates are available.

On Mon, Nov 14, 2011 at 1:29 PM, Juliana Peña
reply@reply.github.com
wrote:

**Comment by barend** [comment]
I like this. It's a nice "premium feature" to drive sales: the app isn't crippled without it, but the extended timeouts have great added value to encourage people to buy.

Maybe you could send a force logout message to the client app when the timeout expires. It'll help prevent confusion and the message box makes a great place to put an "upgrade to plus" button.

**Comment by lhchavez** [comment]
We will be releasing 1.5 soon (sorry, we were swamped with work).

At first, even if you have the plus version, the timeout will be of 2h. Once the release is out in all markets, I'll start making the server-side change to have an extended timeout for plus users. Please allow a couple of weeks after the release for this feature to be fully active.

**Comment by dajunga** [comment]
Nice!!!

On Wed, Apr 4, 2012 at 7:43 PM, lhchavez <
reply@reply.github.com

**Comment by lhchavez** [comment]
Due to a bug in 1.5, we couldn't enable it. Fixed for real in 1.6.
