### ISSUE TITLE
UI Like Pc

### ISSUE THREAD

**Issue by ankitm10** [lhchavez/gtalkchat#83]
can you make the UI like the one we use on our pc ? like the same signing in usename password same logo it would nice. 
and make the background colour white. i know changing from settings>theme i can change the background. i would like the orignal google talk look everyone would. and the option to choose chat theme thanks waiting for ur reply ankit.mirkar@hotmail.com keep up the good work. :)

**Comment by limitedmage** [comment]
What do you mean "google talk look"? Do you have any example screenshots? 

We are trying to make the app as close to the native Windows Phone messaging experience as possible and adhering to the Metro guidelines, so this may not be possible given our objectives.

Thanks for the suggestion :)

**Comment by limitedmage** [comment]
Will close this as no-fix since it was never clarified
