### ISSUE TITLE
Autocorrect not working

### ISSUE THREAD

**Issue by somefloating** [lhchavez/gtalkchat#93]
SUMMARY
The auto-correct in GCHAT 1.3 is not working.  

STEPS TO REPRODUCE
1. Open GCHAT 1.3
2. Start a new conversation.
3. Misspell the world "Test" by typing "Tesy" and press the space bar.   Note that although the keyboard recommends "Test", it doesn't autocorrect.
4. Press the WINDOWS key to return to the START SCREEN.
5. Open the native SMS application MESSAGING on windows phone.
6. Start a new thread.
7. Misspell the word "Test" by typing "Tesy" and press the space bar.  Note that the native messaging application does correct the word.  It is automatically change to "Test" without further user interaction.

EXPECTED RESULT:  Words are auto-corrected in GCHAT.
ACTUAL RESULT:  Words are not autocorrect in GCHAT.  Only typing suggestions are displayed to the user.  Users must click on each misspelled word to correct it.

ADDITIONAL INFORMATION:
GCHAT: Version 1.3
DEVICE: Samsung Focus S (SGH-i937)
CARRIER: ATT
Software: Windows Phone 7.5
OS version 7.10.7720.68

**Comment by lhchavez** [comment]
huh, this is extremely weird. will take a look into it, we will try to fix it by next release.

**Comment by limitedmage** [comment]
Apparently InputScope=Chat is not as magical as I had once thought u_u This issue has been fixed, expect it to ship with 1.4 soon :)

**Comment by limitedmage** [comment]
Also, thanks for the very detailed bug report!! :D

**Comment by somefloating** [comment]
Awesome.  Yeah, I'm shocked.  I figure u guys just set it to "text" instead for the fix.  Totally weird.  Your app rocks by the way.

**Comment by beebeeep** [comment]
The bug still appears, supposedly while typing not in English (tested with Russian language). Of course, russian spelling is supported by phone (it works well on browser, facebook chat, email etc)

**Comment by beebeeep** [comment]
P.S. version 1.5 from marketplace,
